spring.application.name=news

spring.datasource.url=jdbc:mysql://localhost:3306/news
spring.datasource.username=root
spring.datasource.password=

newsapi.key=dc38c9e4676a4df5bbff34f354b70ca2
newsapi.url=https://newsapi.org/v2/everything

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
